Module5 task1
htmlacademy-javascript/2065357-keksobooking-27 pull request #5
Opened 2022-10-05 11:00 UTC by Vanesflat

2022-10-06 09:20 UTC, Dima-Dim requested changes

2022-10-06 09:20 UTC, Dima-Dim commented on js/util.js
> +    max = min;
Не нужно переопределять переданные в функцию переменные, так очень легко запутаться где есть что.

2022-10-07 04:10 UTC, Dima-Dim commented on js/data.js
> +const COORDINATES = { MIN_LAT: 35.65000, MAX_LAT: 35.70000, MIN_LNG: 139.70000, MAX_LNG: 139.80000, NUMBER_OF_DECIMALS: 5 };
Очень плохо читаемый объект. Не нужно экономить строки, в ущерб читаемости.

2022-10-07 04:11 UTC, merged

2022-10-07 05:23 UTC, Vanesflat commented on js/data.js
> +const COORDINATES = { MIN_LAT: 35.65000, MAX_LAT: 35.70000, MIN_LNG: 139.70000, MAX_LNG: 139.80000, NUMBER_OF_DECIMALS: 5 };
Ок, переделаю в следующем задании.